export interface Article {
  slug: string;
  title: string;
  type: 'Buying Guide' | 'Comparison' | 'Review' | 'Explainer' | 'Setup Guide';
  time: string;
  date: string;
  excerpt: string;
  tags: string[];
  heroColor: string;
  icon: string;
}

export const ARTICLES: Article[] = [
  { slug: 'best-gaming-laptops-2026', title: 'Best Gaming Laptops of 2026', type: 'Buying Guide', time: '8 min', date: 'Jul 15, 2026', excerpt: 'Compare the latest high-performance machines with RTX graphics and OLED displays — from budget picks to 4K monsters.', tags: ['gaming', 'laptops', 'RTX'], heroColor: 'from-red-500/30', icon: '🎮' },
  { slug: 'mechanical-vs-optical-switches', title: 'Mechanical vs Optical Switches: Which Is Right for You?', type: 'Comparison', time: '6 min', date: 'Jul 12, 2026', excerpt: 'Which keyboard switches reign supreme for competitive gaming versus everyday typing? We break down the science.', tags: ['keyboards', 'switches', 'gaming'], heroColor: 'from-blue-500/30', icon: '⌨️' },
  { slug: 'best-gaming-monitors-2026', title: 'Best Gaming Monitors for Every Budget', type: 'Buying Guide', time: '7 min', date: 'Jul 08, 2026', excerpt: 'Refresh rates, HDR, response times explained and our top picks for each price bracket — 1080p to 4K.', tags: ['monitors', 'gaming', 'display'], heroColor: 'from-cyan-500/30', icon: '🖥️' },
  { slug: 'top-wireless-headphones-2026', title: 'Top Wireless Headphones 2026: ANC, Sound & Value', type: 'Comparison', time: '8 min', date: 'Jul 03, 2026', excerpt: 'We tested the top 10 models for sound quality, comfort, ANC performance, and battery life — here are the winners.', tags: ['audio', 'headphones', 'wireless'], heroColor: 'from-purple-500/30', icon: '🎧' },
  { slug: 'best-budget-gaming-mice', title: 'Best Budget Gaming Mice Under ₹5,000', type: 'Buying Guide', time: '5 min', date: 'Jun 28, 2026', excerpt: 'Precision on a budget. You don\'t need to overspend to get flawless tracking, lightweight design, and great sensors.', tags: ['mouse', 'gaming', 'budget'], heroColor: 'from-green-500/30', icon: '🖱️' },
  { slug: 'ssd-vs-hdd-guide', title: 'SSD vs HDD: The Complete Storage Guide', type: 'Explainer', time: '9 min', date: 'Jun 22, 2026', excerpt: 'Storage decisions made simple. When you still need spinning rust and when NVMe is mandatory — PCIe 3.0 vs 4.0 vs 5.0.', tags: ['storage', 'SSD', 'hardware'], heroColor: 'from-orange-500/30', icon: '💾' },
  { slug: 'best-student-laptops-2026', title: 'Best Laptops for Students in 2026', type: 'Buying Guide', time: '7 min', date: 'Jun 18, 2026', excerpt: 'Balancing battery life, portability, and budget. Our top picks for college, engineering, creative arts, and medical students.', tags: ['laptops', 'students', 'budget'], heroColor: 'from-emerald-500/30', icon: '🎓' },
  { slug: 'laptop-buying-guide-2026', title: 'The Ultimate Laptop Buying Guide: Everything You Need to Know', type: 'Buying Guide', time: '10 min', date: 'Jun 15, 2026', excerpt: 'CPU, GPU, RAM, display, battery — what actually matters and what\'s just marketing hype. Make an informed decision.', tags: ['laptops', 'guide', 'beginners'], heroColor: 'from-blue-500/30', icon: '💻' },
  { slug: 'best-mechanical-keyboards-2026', title: 'Best Mechanical Keyboards for Every Use Case', type: 'Buying Guide', time: '8 min', date: 'Jun 10, 2026', excerpt: 'From coding to gaming to office work — find the perfect mechanical keyboard with the right switches for your fingers.', tags: ['keyboards', 'mechanical', 'switches'], heroColor: 'from-violet-500/30', icon: '⌨️' },
  { slug: 'gaming-mouse-buying-guide', title: 'How to Choose the Perfect Gaming Mouse', type: 'Buying Guide', time: '6 min', date: 'Jun 05, 2026', excerpt: 'Sensor types, weight, grip styles, DPI myths, and wireless vs wired — everything that actually affects your aim.', tags: ['mouse', 'gaming', 'guide'], heroColor: 'from-pink-500/30', icon: '🎯' },
  { slug: 'best-nvme-ssds-2026', title: 'Best NVMe SSDs for Speed, Capacity & Value', type: 'Buying Guide', time: '7 min', date: 'Jun 01, 2026', excerpt: 'From budget DRAM-less drives to PCIe 5.0 monsters — find the right SSD for your build, laptop, or PS5 upgrade.', tags: ['SSD', 'storage', 'NVMe'], heroColor: 'from-amber-500/30', icon: '🚀' },
  { slug: 'monitor-buying-guide-2026', title: 'Monitor Buying Guide: Resolution, Refresh Rate & Panel Types', type: 'Explainer', time: '9 min', date: 'May 28, 2026', excerpt: 'IPS vs VA vs OLED. 60Hz vs 144Hz vs 240Hz. 1080p vs 1440p vs 4K. Learn what each spec actually means.', tags: ['monitors', 'display', 'guide'], heroColor: 'from-cyan-500/30', icon: '📺' },
  { slug: 'best-wifi-routers-2026', title: 'Best Wi-Fi Routers for Home & Gaming', type: 'Buying Guide', time: '6 min', date: 'May 25, 2026', excerpt: 'Wi-Fi 6 vs Wi-Fi 6E vs Wi-Fi 7, mesh systems explained, and the best routers for apartments, houses, and gaming.', tags: ['networking', 'WiFi', 'routers'], heroColor: 'from-sky-500/30', icon: '📡' },
  { slug: 'budget-smartphones-2026', title: 'Best Budget Smartphones Under ₹25,000', type: 'Buying Guide', time: '7 min', date: 'May 22, 2026', excerpt: 'Flagship features without the flagship price. Camera quality, battery life, software experience — ranked for India.', tags: ['smartphones', 'budget', 'mobile'], heroColor: 'from-rose-500/30', icon: '📱' },
  { slug: 'best-tablets-2026', title: 'Best Tablets for Work, Study & Entertainment', type: 'Buying Guide', time: '6 min', date: 'May 18, 2026', excerpt: 'iPad vs Android vs Windows tablets. Which one fits your workflow — note-taking, drawing, media, or productivity?', tags: ['tablets', 'mobile', 'iPad'], heroColor: 'from-indigo-500/30', icon: '📟' },
  { slug: 'best-wireless-earbuds-2026', title: 'Best True Wireless Earbuds for Every Budget', type: 'Buying Guide', time: '7 min', date: 'May 15, 2026', excerpt: 'ANC quality, sound signature, battery life, and fit — our honest picks from ₹2,000 to ₹25,000.', tags: ['audio', 'earbuds', 'wireless'], heroColor: 'from-teal-500/30', icon: '🎵' },
  { slug: 'noise-cancelling-headphones-guide', title: 'Active Noise Cancellation Explained: How It Works and What to Buy', type: 'Explainer', time: '8 min', date: 'May 12, 2026', excerpt: 'ANC technology explained in plain English. Feedforward vs feedback vs hybrid — and our top headphone picks.', tags: ['audio', 'ANC', 'headphones'], heroColor: 'from-purple-500/30', icon: '🔇' },
  { slug: 'best-power-banks-2026', title: 'Best Power Banks for Laptops, Phones & Travel', type: 'Buying Guide', time: '5 min', date: 'May 08, 2026', excerpt: 'Capacity, charging speeds, GaN technology, and airline regulations — find the right power bank for your devices.', tags: ['accessories', 'charging', 'travel'], heroColor: 'from-yellow-500/30', icon: '🔋' },
  { slug: 'best-usb-c-hubs-2026', title: 'Best USB-C Hubs & Docking Stations for Laptops', type: 'Buying Guide', time: '6 min', date: 'May 05, 2026', excerpt: 'HDMI, Ethernet, SD cards, USB-A — restore every port your thin laptop eliminated. Budget to Thunderbolt 4 options.', tags: ['accessories', 'USB-C', 'docks'], heroColor: 'from-blue-500/30', icon: '🔌' },
  { slug: 'laptop-cooling-pads-guide', title: 'Do Laptop Cooling Pads Actually Work?', type: 'Explainer', time: '5 min', date: 'May 01, 2026', excerpt: 'We tested 8 cooling pads with thermal cameras. Here\'s when they help, when they\'re useless, and which ones to buy.', tags: ['laptops', 'cooling', 'accessories'], heroColor: 'from-red-500/30', icon: '❄️' },
  { slug: 'graphics-cards-buying-guide', title: 'Graphics Card Buying Guide: NVIDIA vs AMD vs Intel', type: 'Buying Guide', time: '9 min', date: 'Apr 28, 2026', excerpt: 'VRAM requirements, ray tracing, DLSS vs FSR, and which GPU you actually need for your resolution and games.', tags: ['GPU', 'graphics', 'gaming'], heroColor: 'from-green-500/30', icon: '🎨' },
  { slug: 'best-gaming-chairs-2026', title: 'Best Gaming & Ergonomic Chairs for Long Sessions', type: 'Buying Guide', time: '7 min', date: 'Apr 25, 2026', excerpt: 'Your back deserves better. Ergonomic chairs vs gaming chairs — lumbar support, materials, and what actually matters.', tags: ['chairs', 'ergonomics', 'gaming'], heroColor: 'from-slate-500/30', icon: '🪑' },
  { slug: 'mechanical-switch-buying-guide', title: 'Mechanical Keyboard Switches: The Complete Reference', type: 'Explainer', time: '8 min', date: 'Apr 22, 2026', excerpt: 'Linear vs Tactile vs Clicky. Cherry MX, Gateron, Kailh — actuation force, travel distance, and finding your perfect switch.', tags: ['keyboards', 'switches', 'mechanical'], heroColor: 'from-fuchsia-500/30', icon: '🔘' },
  { slug: 'laptop-accessories-guide', title: 'Essential Laptop Accessories Every User Should Own', type: 'Buying Guide', time: '6 min', date: 'Apr 18, 2026', excerpt: 'From laptop stands to portable monitors to travel chargers — the accessories that transform your workflow.', tags: ['laptops', 'accessories', 'productivity'], heroColor: 'from-lime-500/30', icon: '🧰' },
  { slug: 'study-setup-guide', title: 'How to Build the Perfect Study Setup on a Budget', type: 'Setup Guide', time: '7 min', date: 'Apr 15, 2026', excerpt: 'Desk, chair, monitor, lighting, and organisation — a complete student workspace under ₹20,000 that boosts focus.', tags: ['setup', 'students', 'budget'], heroColor: 'from-emerald-500/30', icon: '📚' },
  { slug: 'programming-laptop-guide', title: 'What Laptop Specs Actually Matter for Programming', type: 'Buying Guide', time: '7 min', date: 'Apr 12, 2026', excerpt: 'More RAM vs faster CPU. Integrated GPU vs dedicated. Linux compatibility, keyboard quality, and display considerations.', tags: ['programming', 'laptops', 'developers'], heroColor: 'from-blue-500/30', icon: '👨‍💻' },
  { slug: 'streaming-equipment-guide', title: 'Streaming Equipment Guide: From Beginner to Pro', type: 'Setup Guide', time: '8 min', date: 'Apr 08, 2026', excerpt: 'Microphones, cameras, capture cards, lighting, and software — build your streaming setup step by step.', tags: ['streaming', 'setup', 'content'], heroColor: 'from-purple-500/30', icon: '🎥' },
  { slug: 'best-webcams-2026', title: 'Best Webcams for Remote Work & Streaming', type: 'Buying Guide', time: '6 min', date: 'Apr 05, 2026', excerpt: '1080p vs 4K, autofocus, low-light performance, and built-in mics — find the right webcam for your setup.', tags: ['webcams', 'streaming', 'remote work'], heroColor: 'from-cyan-500/30', icon: '📷' },
  { slug: 'best-usb-microphones-2026', title: 'Best USB Microphones for Podcasting, Streaming & Calls', type: 'Buying Guide', time: '6 min', date: 'Apr 01, 2026', excerpt: 'Condenser vs dynamic, sample rates, polar patterns — and our top picks from ₹3,000 to ₹20,000.', tags: ['microphones', 'audio', 'streaming'], heroColor: 'from-rose-500/30', icon: '🎙️' },
  { slug: 'productive-desk-setup-guide', title: 'How to Build a Productive Desk Setup That Lasts', type: 'Setup Guide', time: '8 min', date: 'Mar 28, 2026', excerpt: 'Ergonomics, cable management, monitor placement, lighting, and the tools that make working at your desk a joy.', tags: ['setup', 'productivity', 'ergonomics'], heroColor: 'from-amber-500/30', icon: '🖥️' },
];
